### PR TITLE
[SE-4510] fix: update models to work with Koa

### PR DESCRIPTION
**Pull request by gabor-boros**
This registration form is not compatible with Koa. To make it compatible, we need to adjust the models and migrations.

**Dependencies**: None

**Testing instructions**:

1. Install the package on Koa using the readme of the repo (already installed [here](https://campus-koa.opencraft.hosting/register)
2. Check the "support education research..." checkbox
3. Validate the form that appeared

**Author notes and concerns**:

N/A

**Reviewers**
- [ ] @nizarmah

### CODE REVIEW

**Comment by clemente** [comment]
@gabor-boros I didn't check in detail, but after a quick look: It may be better to add a migration instead of modifying the existing one. Unless the old migrations stopped working.

**Comment by gabor-boros** [comment]
> @gabor-boros I didn't check in detail, but after a quick look: It may be better to add a migration instead of modifying the existing one. Unless the old migrations stopped working.

@clemente We cannot do that as the first migration is failing and we cannot run without this change. I believe on_delete was part of Django 1.8 as well but wasn't required, so it should work.

**Comment by clemente** [comment]
@gabor-boros 

- Could you avoid the fork https://github.com/open-craft/custom-registration-form/, and use https://github.com/edx-olive/custom-registration-form/ to create your branch there? It's better if we have it in a central place (in edx-olive repositories). 
Note that the edx-olive repositories and Campus infrastructure is in the process of being transferred to Israeli companies, so we shouldn't depend on our OpenCraft repositories; we should use edx-olive's.

- The form was indeed installed on the sandbox but it looks that without the migrations, because I saw `django.db.utils.ProgrammingError: (1146, "Table 'campuskoa_opencraft_hosting_edxapp.custom_reg_form_extrainfo' doesn't exist")`. However, I'm trying to run them with `./manage.py lms migrate custom_reg_form` (inside virtualenv) and it says `CommandError: App 'custom_reg_form' does not have migrations.`. It's right! `/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/custom_reg_form/` doesn't have the `migrations` folder. Is this expected? Did it change with Koa? Do you need to change `packages=['custom_reg_form'],` to `packages=['custom_reg_form', 'custom_reg_form.migrations'],` in `setup.py`? (Maybe the `locale` folder too?)

- There seems to be a difference in the layout. Currently in Ginkgo [you can see](https://courses.stage.campus.gov.il/register) that the marketing checkbox is visible from the start. But in Koa, I don't see the marketing checkbox; I see `Support education research by providing additional information`, I need to click it and then the new fields appear, among them the `I hereby confirm receiving updates on new courses, content and new learning initiatives (optional)`. This makes sense: it is indeed `additional information` that students can fill. But I wonder whether Campus's lawyers want this checkbox to be visible outside the form. This change is probably due to Koa and we may need a new implementation of the checkbox for Koa. The lawyers may require an explicit checkbox to agree to ToS (as currently in Ginkgo) and this isn't in Koa. I think reimplementing this form can be outside the scope of the upgrade and we should add some points to the document and prepare a backlog of small things to fix after the upgrade. There's a section at the bottom of the document; could you add a task there, or in the section about the reg. form? (CC @itsjeyd)

I'll continue testing after the migration issue is solved. To test it I'll create 2 users, one accepting and another not accepting, and I'll check that the DB stores the preference.

The code looks good. We already discussed that it's not harmful for production (because the migrations are already applied). I hope…

**Comment by gabor-boros** [comment]
@clemente 

> Could you avoid the fork https://github.com/open-craft/custom-registration-form/, and use https://github.com/edx-olive/custom-registration-form/ to create your branch there? It's better if we have it in a central place (in edx-olive repositories). Note that the edx-olive repositories and Campus infrastructure is in the process of being transferred to Israeli companies, so we shouldn't depend on our OpenCraft repositories; we should use edx-olive's.

Of course, but in that case, may I request push access from you? As far as I remember correctly, I had no access, that's the reason for the fork.

> The form was indeed installed on the sandbox but it looks that without the migrations, because I saw django.db.utils.ProgrammingError: (1146, "Table 'campuskoa_opencraft_hosting_edxapp.custom_reg_form_extrainfo' doesn't exist"). However, I'm trying to run them with ./manage.py lms migrate custom_reg_form (inside virtualenv) and it says CommandError: App 'custom_reg_form' does not have migrations.. It's right! /edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/custom_reg_form/ doesn't have the migrations folder. Is this expected? Did it change with Koa? Do you need to change packages=['custom_reg_form'], to packages=['custom_reg_form', 'custom_reg_form.migrations'], in setup.py? (Maybe the locale folder too?)

That's strange. When I tested it locally when I checked the theme, it was migrated properly after my fix. Let me double-check it today/tomorrow.

> But I wonder whether Campus's lawyers want this checkbox to be visible outside the form. This change is probably due to Koa and we may need a new implementation of the checkbox for Koa. The lawyers may require an explicit checkbox to agree to ToS (as currently in Ginkgo) and this isn't in Koa. 

That's maybe related to the theme that we show it anyway. Let me check this too.

**Comment by clemente** [comment]
@gabor-boros I don't know why I had to manually add members (doesn't all OpenCraft get access…? It seems that just a few people from Campus project had „owner“ access, I don't know why). I added you with write access, let me know if it works.

**Comment by clemente** [comment]
I changed the task number as mentioned above by github

**Comment by gabor-boros** [comment]
FTR: This PR was closed in favor of https://github.com/edx-olive/custom-registration-form/pull/3

**Pull request closed without merging**
